const API='/api';
const $=s=>document.querySelector(s);
const token=()=>localStorage.getItem('ecocycle_token');
function msg(id,text,ok=false){const e=document.getElementById(id);if(!e)return;e.textContent=(ok?'✓ ':'')+text;e.className='form-message '+(ok?'success':'');e.style.display='block'}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token())headers.Authorization='Bearer '+token();const r=await fetch(API+path,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||'Something went wrong.');return d}
function updateAuthUI(){const a=$('.nav-login');if(a&&token()){a.textContent='Account';a.href='dashboard.html'}}
document.addEventListener('DOMContentLoaded',()=>{
 const y=$('#year');if(y)y.textContent=new Date().getFullYear(); updateAuthUI();
 $('.menu-btn')?.addEventListener('click',()=>$('.nav')?.classList.toggle('open'));
 $('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});localStorage.setItem('ecocycle_token',d.token);localStorage.setItem('ecocycle_user',JSON.stringify(d.user));msg('loginMessage','Signed in successfully. Opening dashboard...',true);setTimeout(()=>location.href='dashboard.html',500)}catch(err){msg('loginMessage',err.message)}});
 $('#signupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirmPassword'))return msg('signupMessage','Passwords do not match.');try{const d=await api('/auth/signup',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),password:f.get('password')})});localStorage.setItem('ecocycle_token',d.token);localStorage.setItem('ecocycle_user',JSON.stringify(d.user));msg('signupMessage','Account created successfully. Opening dashboard...',true);setTimeout(()=>location.href='dashboard.html',600)}catch(err){msg('signupMessage',err.message)}});
 $('#forgotForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/auth/forgot',{method:'POST',body:JSON.stringify({email:f.get('email')})});msg('forgotMessage',d.message,true);if(d.resetUrl){const a=document.createElement('a');a.href=d.resetUrl;a.textContent=' Open demo reset page';a.className='text-link';$('#forgotMessage')?.appendChild(a)}}catch(err){msg('forgotMessage',err.message)}});
 $('#resetForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const tokenParam=new URLSearchParams(location.search).get('token');try{const d=await api('/auth/reset',{method:'POST',body:JSON.stringify({token:tokenParam,password:f.get('password')})});msg('resetMessage',d.message,true);setTimeout(()=>location.href='login.html',900)}catch(err){msg('resetMessage',err.message)}});
 $('#pickupForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);if(!token()){msg('pickupMessage','Please sign in before scheduling a pickup.');return}try{const d=await api('/pickups',{method:'POST',body:JSON.stringify({deviceType:f.get('device'),quantity:f.get('quantity'),preferredDate:f.get('date'),address:f.get('address')})});msg('pickupMessage',d.message+' Your EcoPoints were updated.',true);e.target.reset()}catch(err){msg('pickupMessage',err.message)}});
 $('#contactForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);try{const d=await api('/contact',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),message:f.get('message')})});msg('contactMessage',d.message,true);e.target.reset()}catch(err){msg('contactMessage',err.message)}});
 $('#logoutBtn')?.addEventListener('click',()=>{localStorage.removeItem('ecocycle_token');localStorage.removeItem('ecocycle_user');location.href='login.html'});
 document.querySelectorAll('.faq button').forEach(btn=>btn.addEventListener('click',()=>{const ans=btn.nextElementSibling;const open=ans.style.display==='block';document.querySelectorAll('.faq p').forEach(x=>x.style.display='none');document.querySelectorAll('.faq button span').forEach(x=>x.textContent='+');if(!open){ans.style.display='block';btn.querySelector('span').textContent='−'}}));
 loadDashboard(); loadCentres();
});
async function loadDashboard(){if(!$('#dashboardStats'))return;if(!token()){location.href='login.html';return}try{const d=await api('/dashboard');const s=d.stats;$('#points').textContent=s.points;$('#devices').textContent=s.devices;$('#waste').textContent=s.wasteKg.toFixed(1)+' kg';$('#streak').textContent=s.streak+' days';const box=$('#pickupList');if(box)box.innerHTML=d.pickups.length?d.pickups.map(p=>`<div class="quick-card"><b>${p.device_type}</b><p>${p.quantity} item(s) · ${p.preferred_date}</p><small>Status: ${p.status}</small></div>`).join(''):'<p>No pickups yet. Start by scheduling your first e-waste pickup.</p>';const u=JSON.parse(localStorage.getItem('ecocycle_user')||'{}');$('#welcomeName')&&(($('#welcomeName').textContent=u.name||'Eco Champion'));}catch(e){if(e.message.includes('session')){localStorage.removeItem('ecocycle_token');location.href='login.html'}}}
async function loadCentres(){if(!$('#centreGrid'))return;try{const d=await api('/centres');$('#centreGrid').innerHTML=d.centres.map(c=>`<article class="centre-card"><span>📍</span><div><h3>${c.name}</h3><p>${c.address}</p><small>${c.hours}</small></div></article>`).join('')}catch(e){}}
